# Generated by Django 2.2.13 on 2020-06-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='image_blog/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='pub_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
